config/routes.rb
Friggione::Application.routes.draw do
  
  root :to => "recipes#index"
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  resources :instructions
  resources :ingredients
  resources :recipes

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :recipe

  mount_uploader :photo, PhotoUploader
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  
  belongs_to :user
  
  has_many :ingredients,  dependent: :destroy
  has_many :instructions, dependent: :destroy
  
  accepts_nested_attributes_for :ingredients, :reject_if => lambda { |a| a[:content].blank? },  :allow_destroy => true
  accepts_nested_attributes_for :instructions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
  mount_uploader :photo, PhotoUploader
  mount_uploader :video, VideoUploader
  
  extend FriendlyId
  friendly_id :title, use: :history

  def should_generate_new_friendly_id?
    new_record?
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :recipes
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end

  def update_with_omniauth(auth)
    self.update_attributes!( {:name => auth["info"]["name"], :image => auth["info"]["image"] })
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.includes([:ingredients, :instructions]).order(:created_at).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build 
    @recipe.instructions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    # raise params.inspect
    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    # raise auth.to_yaml
    
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    
    
    user.update_with_omniauth(auth)
    
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => ""}Friggione.it
      .nav-collapse
        %ul.nav
          %li= link_to "Ricette", "/recipes"
          - unless current_user.nil?
            %li= link_to "Nuova ricetta", "/recipes/new"
          
        .pull-right
          %ul.nav
            - if current_user
              %li.dropdown
                %a{ class: "dropdown-toggle", href: "#", "data-toggle" => "dropdown" }
                  %img.size19{ src: "#{current_user.image}" }
                  %b.caret
                %ul.dropdown-menu
                  %li.current-user
                    %a                      
                      = current_user.name
                    
                  %li
                    = link_to "Sign Out", signout_path
            - else
              %li
                %a{ href: "/auth/twitter" }
                  %img{ src: "#{asset_path('sign-in-with-twitter-d.png')}", alt: "Sign in with twitter"}
              %li
                %a{ href: "/auth/facebook" }
                  %img{ src: "#{asset_path('facebook-login-button.png')}", alt: "Sign in with facebook"}

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Friggione"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag    "application"

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0"}

    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    = render :partial => 'layouts/header'
    .container.page

      .row
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Ricette", "/recipes"
              - unless current_user.nil?
                %li= link_to "Nuova ricetta", "/recipes/new"
              
        .span9
          = yield
    
      %footer
        %p &copy; taxSoft 2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = javascript_include_tag "http://cdn.sublimevideo.net/js/q764co1l.js"
    

app/views/recipes/_form.html.haml
.well
  %fieldset
    %legend My Recipe
    .control-group
      %label.control-label{ for: :title } Title
      .controls
        = f.text_field :title, :class => 'input-xlarge'
      
    .control-group
      %label.control-label{ for: :summary } Summary
      .controls
        = f.text_area :summary, :class => 'input-xlarge', rows: 3

    .control-group
      %label.control-label{ for: :author } Author
      .controls
        = f.text_field :author, :class => 'input-large'

    .control-group
      %label.control-label{ for: :yield } Yield
      .controls
        = f.text_field :yield, :class => 'input-large'

    .control-group
      %label.control-label{ for: :photo } Photo
      .controls
        = f.file_field :photo, class: 'input-large'
    
    .control-group
      %label.control-label{ for: :video } Video
      .controls
        = f.file_field :video, class: 'input-large'

.well      
  %fieldset
    %legend Ingredients
    = f.fields_for :ingredients do |ingredient|
      .control-group
        .controls.form-inline
          = ingredient.text_field :content, :class => 'input-medium', :placeholder => 'Ingredient'
          = ingredient.text_field :um,      :class => 'input-small',  :placeholder => 'Type'
          = ingredient.text_field :value,   :class => 'input-small',  :placeholder => 'Value'
          = ingredient.link_to_remove raw("<i class='icon-minus icon-white'></i>"), class: "btn btn-danger btn-mini"

    = f.link_to_add raw("<i class='icon-plus icon-white'></i>ingredient"), :ingredients, class: "btn btn-success  btn-mini"
    
.well        
  %fieldset
    %legend Instructions
    = f.fields_for :instructions do |instruction|
      .control-group
        .controls
          = instruction.text_area :content, :class => 'input-xlarge', rows: 3
          = instruction.link_to_remove raw("<i class='icon-minus icon-white'></i>"), class: "btn btn-danger btn-mini"

      .control-group
        %label.control-label{ for: :photo } Photo
        .controls
          = instruction.file_field :photo, class: 'input-large'

    = f.link_to_add raw("<i class='icon-plus icon-white'></i>instruction"), :instructions, class: "btn btn-success btn-mini"
    

.form-actions.well
  %button{:class => "btn btn-primary btn-large", :type => "submit"} Save
  or
  = link_to "Cancel", recipes_path

app/views/recipes/_recipe.html.haml
%div
  .item.hrecipe
    %small.time
      %time.timeago{ datetime: "#{time_ago_in_words(recipe.created_at)}"}
    %a{ href: "#{recipe_path(recipe)}"}
      
      %img.avatar{ src: "#{recipe.photo_url(:small_thumb)}", alt: "#{recipe.title}"}
      %strong.fullname= recipe.title

    %span.destinatario
      %i= "@#{recipe.author}"

    %p= recipe.summary
  %a
    

app/views/recipes/edit.html.haml
= nested_form_for @recipe, :url => recipe_path(@recipe), :html => { :class => "form-horizontal edit_recipe", :id => "edit_recipe" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/recipes/index.html.haml
.content-main
  .content-header
    .header-inner
      %h2 Ricette
  
  #items.recipes
    - @recipes.each do |recipe|
      = render recipe
      
    



/ %h1 Recipes
/ %table{:class => "table table-striped"}
/   %thead
/     %tr
/       %th ID
/       %th
/         = t("activerecord.attributes.recipe.title", :default => t("activerecord.labels.title", :default => "Title"))
/       %th Created at
/       %th Actions
/   %tbody
/     - @recipes.each do |recipe|
/       %tr
/         %td= recipe.id
/         %td= link_to recipe.title, recipe_path(recipe)
/         %td= recipe.created_at
/         %td
/           = link_to "Show", recipe_path(recipe)
/           - unless current_user.nil?
/             = link_to "Edit", edit_recipe_path(recipe)
/             = link_to "Destroy", recipe_path(recipe), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
/ 
/ - unless current_user.nil?
/   = link_to "New Recipe", new_recipe_path, :class => 'btn btn-primary'

app/views/recipes/new.html.haml
= nested_form_for @recipe, :url => recipes_path, :html => { :class => "form-horizontal"} do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/recipes/show.html.haml
%div.hrecipe.well
  %h2.fn= @recipe.title
  
  %span.author= "@#{@recipe.author}"
  .datePublished= "posted #{time_ago_in_words(@recipe.created_at)} ago"
  - unless @recipe.video.blank?
    .video
      %a.sublime{ href: "#{@recipe.video}" }
        %i.icon-facetime-video
        watch video
      %video.sublime.zoom{ style: "display:none", width: "640", height: "360", preload: "none"}
        %source{ src: "#{@recipe.video}" }
  %br
  %br
  %p.summary= @recipe.summary
  = image_tag @recipe.photo_url(:thumb), alt: "#{@recipe.title}" unless @recipe.photo.blank?
  
  %section.ingredients
    %h3 Ingredients
    %ul
      - for i in @recipe.ingredients.order("ingredients.id asc") do
        %li.ingredient= i.content

  %section.instructions
    %h3 Instructions
    - for i in @recipe.instructions.order("instructions.id asc") do
      %dl{ class: "instruction alt"}
        %dd.img
          = image_tag i.photo unless i.photo.blank?
          / %img{ src: "#{i.photo}"}
        %dd
          = i.content
    
  .form-actions
    = link_to "Back", recipes_path, :class => 'btn'
    - unless current_user.nil?
      = link_to "Edit", edit_recipe_path(@recipe), :class => 'btn'
      = link_to "Delete", recipe_path(@recipe), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'

         